header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Canonical Ltd.
    content: |
      Copyright [year] [owner]
      See LICENSE file for licensing details.
    pattern: |
      Copyright \d{4} Canonical Ltd.
      See LICENSE file for licensing details.
  paths:
    - "charms/**"
  paths-ignore:
    - "**/.gitkeep"
    - "**/*.cfg"
    - "**/*.conf"
    - "**/*.j2"
    - "**/*.json"
    - "**/*.md"
    - "**/*.rst"
    - "**/*.rule"
    - "**/*.svg"
    - "**/*.tmpl"
    - "**/*.tsv"
    - "**/*.txt"
    - "**/*.xml"
    - "**/*.md.j2"
    - "**/*.rst.j2"
    - "**/.codespellignore"
    - "**/.dockerignore"
    - "**/.flake8"
    - "**/.jujuignore"
    - "**/.gitignore"
    - "**/.licenserc.yaml"
    - "**/.trivyignore"
    - "**/.woke.yaml"
    - "**/.woke.yml"
    - "**/CODEOWNERS"
    - "**/icon.svg"
    - "**/LICENSE"
    - "**/trivy.yaml"
    - "**/zap_rules.tsv"
    - "**/pyproject.toml"
    - "**/uv.lock"
    - "charms/*/lib/**"
    - "charms/*/*_rock/**"
    - "charms/jenkins-k8s/tests/integration/files/dex.yaml"
    - "charms/jenkins-k8s/tests/integration/files/identity-bundle-edge-patched.yaml"
    - "docs/**"
  comment: on-failure
