# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[testenv]
skipsdist = true
skip_missing_interpreters = true
requires = tox>=4.21
no_package = true
runner = uv-venv-lock-runner
passenv = PYTHONPATH, CHARM_BUILD_DIR, MODEL_SETTINGS, GITHUB_HEAD_REF
setenv =
    PYTHONPATH = {changedir}:{changedir}/lib:{changedir}/src
    PYTHONBREAKPOINT = ipdb.set_trace
    PY_COLORS = 1

[testenv:{jenkins-agent,jenkins-agent-k8s,jenkins-k8s}-fmt]
changedir = charms/{envname}
dependency_groups = fmt
commands =
    ruff check --fix --select I src tests
    ruff format src tests

[testenv:{jenkins-agent,jenkins-agent-k8s,jenkins-k8s}-lint]
changedir = charms/{envname}
dependency_groups = lint
commands =
    codespell {changedir}
    ruff format --check --diff src tests
    ruff check src tests
    mypy src tests

[testenv:{jenkins-agent,jenkins-agent-k8s,jenkins-k8s}-unit]
changedir = charms/{envname}
dependency_groups = unit
commands =
    coverage run --source={changedir}/src -m pytest --ignore={changedir}/tests/integration -v --tb native -s {posargs}
    coverage report

[testenv:{jenkins-agent,jenkins-agent-k8s,jenkins-k8s}-static]
changedir = charms/{envname}
dependency_groups = static
commands =
    bandit -c {toxinidir}/pyproject.toml -r src tests

[testenv:{jenkins-agent,jenkins-agent-k8s,jenkins-k8s}-coverage-report]
changedir = charms/{envname}
dependency_groups = coverage-report
commands =
    coverage report

[testenv:{jenkins-agent,jenkins-agent-k8s,jenkins-k8s}-lint-fix]
changedir = charms/{envname}
dependency_groups = lint
commands =
    ruff check --fix --fix-only src tests

[testenv:jenkins-k8s-integration]
changedir = charms/jenkins-k8s
dependency_groups = integration
commands =
    playwright install --with-deps chromium
    pytest --tb native --ignore={changedir}/tests/unit --log-cli-level=INFO -s --reruns 2 --reruns-delay 30 --only-rerun ConnectionClosedError --only-rerun ProxyNotConnectedError {posargs}

[testenv:{jenkins-agent,jenkins-agent-k8s}-integration]
changedir = charms/{envname}
dependency_groups = integration
commands =
    pytest --tb native --ignore={changedir}/tests/unit --log-cli-level=INFO -s {posargs}
