# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[testenv]
skipsdist = true
skip_missing_interpreters = true
requires = tox>=4.21
no_package = true
runner = uv-venv-lock-runner
passenv = PYTHONPATH, CHARM_BUILD_DIR, MODEL_SETTINGS, GITHUB_HEAD_REF
setenv =
    PYTHONPATH = {changedir}:{changedir}/lib:{changedir}/src
    PYTHONBREAKPOINT = ipdb.set_trace
    PY_COLORS = 1

[testenv:jenkins-agent-fmt]
changedir = charms/jenkins-agent
dependency_groups = fmt
commands =
    ruff check --fix --select I src tests
    ruff format src tests

[testenv:jenkins-agent-k8s-fmt]
changedir = charms/jenkins-agent-k8s
dependency_groups = fmt
commands =
    ruff check --fix --select I src tests
    ruff format src tests

[testenv:jenkins-k8s-fmt]
changedir = charms/jenkins-k8s
dependency_groups = fmt
commands =
    ruff check --fix --select I src tests
    ruff format src tests

[testenv:jenkins-agent-lint]
changedir = charms/jenkins-agent
dependency_groups = lint
commands =
    codespell --toml {toxinidir}/pyproject.toml {changedir}
    ruff format --check --diff src tests
    ruff check src tests
    mypy src tests

[testenv:jenkins-agent-k8s-lint]
changedir = charms/jenkins-agent-k8s
dependency_groups = lint
commands =
    codespell --toml {toxinidir}/pyproject.toml {changedir}
    ruff format --check --diff src tests
    ruff check src tests
    mypy src tests

[testenv:jenkins-k8s-lint]
changedir = charms/jenkins-k8s
dependency_groups = lint
commands =
    codespell --toml {toxinidir}/pyproject.toml {changedir}
    ruff format --check --diff src tests
    ruff check src tests
    mypy src tests

[testenv:jenkins-agent-unit]
changedir = charms/jenkins-agent
dependency_groups = unit
commands =
    coverage run --source={changedir}/src -m pytest --ignore={changedir}/tests/integration -v --tb native -s {posargs}
    coverage report

[testenv:jenkins-agent-k8s-unit]
changedir = charms/jenkins-agent-k8s
dependency_groups = unit
commands =
    coverage run --source={changedir}/src -m pytest --ignore={changedir}/tests/integration -v --tb native -s {posargs}
    coverage report

[testenv:jenkins-k8s-unit]
changedir = charms/jenkins-k8s
dependency_groups = unit
commands =
    coverage run --source={changedir}/src -m pytest --ignore={changedir}/tests/integration -v --tb native -s {posargs}
    coverage report

[testenv:jenkins-agent-static]
changedir = charms/jenkins-agent
dependency_groups = static
commands =
    bandit -c {toxinidir}/pyproject.toml -r src tests

[testenv:jenkins-agent-k8s-static]
changedir = charms/jenkins-agent-k8s
dependency_groups = static
commands =
    bandit -c {toxinidir}/pyproject.toml -r src tests

[testenv:jenkins-k8s-static]
changedir = charms/jenkins-k8s
dependency_groups = static
commands =
    bandit -c {toxinidir}/pyproject.toml -r src tests

[testenv:jenkins-agent-coverage-report]
changedir = charms/jenkins-agent
dependency_groups = coverage-report
commands =
    coverage report

[testenv:jenkins-agent-k8s-coverage-report]
changedir = charms/jenkins-agent-k8s
dependency_groups = coverage-report
commands =
    coverage report

[testenv:jenkins-k8s-coverage-report]
changedir = charms/jenkins-k8s
dependency_groups = coverage-report
commands =
    coverage report

[testenv:jenkins-agent-lint-fix]
changedir = charms/jenkins-agent
dependency_groups = lint
commands =
    ruff check --fix --fix-only src tests

[testenv:jenkins-agent-k8s-lint-fix]
changedir = charms/jenkins-agent-k8s
dependency_groups = lint
commands =
    ruff check --fix --fix-only src tests

[testenv:jenkins-k8s-lint-fix]
changedir = charms/jenkins-k8s
dependency_groups = lint
commands =
    ruff check --fix --fix-only src tests

[testenv:jenkins-k8s-integration]
changedir = charms/jenkins-k8s
dependency_groups = integration
commands =
    playwright install --with-deps chromium
    pytest --tb native --ignore={changedir}/tests/unit --log-cli-level=INFO -s --reruns 2 --reruns-delay 30 --only-rerun ConnectionClosedError --only-rerun ProxyNotConnectedError {posargs}

[testenv:jenkins-agent-integration]
changedir = charms/jenkins-agent
dependency_groups = integration
commands =
    pytest --tb native --ignore={changedir}/tests/unit --log-cli-level=INFO -s {posargs}

[testenv:jenkins-agent-k8s-integration]
changedir = charms/jenkins-agent-k8s
dependency_groups = integration
commands =
    pytest --tb native --ignore={changedir}/tests/unit --log-cli-level=INFO -s {posargs}
