name: jenkins-agent Tests

on:
  pull_request:
    paths:
      - 'charms/jenkins-agent/**'
      - '.github/workflows/jenkins_agent_test.yaml'

jobs:
  unit-tests:
    permissions:
      contents: read
      pull-requests: write
    uses: canonical/operator-workflows/.github/workflows/test.yaml@main
    secrets: inherit
    with:
      working-directory: charms/jenkins-agent
      self-hosted-runner: false
      vale-style-check: false
      with-uv: true
